name: Distribute APK to Firebase

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  distribute-apk:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"

      # Step 3: Verify Flutter Installation
      # - name: Verify Flutter Installation
      #   run: flutter doctor -v

      # Step 4: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 5: Build the release APK
      - name: Build APK
        run: flutter build apk --debug

      # Step 6: Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Step 7: Authenticate Firebase CLI
      # - name: Authenticate Firebase
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      #   run: firebase login:ci

      # # Step 8: Distribute APK to Firebase App Distribution
      - name: Distribute APK
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-debug.apk \
          --app 1:981212150058:android:d7a644e30d78b0982ac653 \
          --release-notes "test_build" \
          --groups my_team
