name: Distribute APK to Firebase

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  distribute-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"

      - name: Verify Flutter Installation
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --debug

      # - name: Install Firebase CLI
      #   run: npm install -g firebase-tools

      # - name: Distribute APK
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      #   run: |
      #     firebase appdistribution:distribute build/app/outputs/flutter-apk/app-debug.apk \
      #     --app 1:981212150058:android:d7a644e30d78b0982ac653 \
      #     --release-notes "test_build" \
      #     --groups my_team
      - name: Upload Artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.APPID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: my_team
          file: build/app/outputs/flutter-apk/app-debug.apk
          releaseNotes: "Release for ${{ github.ref }}\n\n${{ steps.get_tag_message.outputs.tag-message }}"
          releaseNotesFile: ""
          appRelease: ${{ steps.extract_version.outputs.version }}
